Imposto la cartella home

In [1]:
home_path = "E:\\Datasets\\NL3"

# Categorizzazione delle windows

## Importo le librerie utili

In [2]:
import numpy as np
import os
import pandas as pd
import mne

## Funzione ausiliaria

Creo una funzione ausiliaria per estrarre le colonne di una matrice

In [3]:
def column(matrix, i):
    return [row[i] for row in matrix]

## Importo i dati

Importo i dati e i concepts di THINGS

In [4]:
things_path = os.path.join(home_path, "things_concepts.tsv")

categories = pd.read_csv(things_path, sep='\t')

In [5]:
categories

Word         uniqueID              Example image  Bigram  \
0            aardvark         aardvark  https://imgur.com/LAJGlN0       0   
1              abacus           abacus  https://imgur.com/peZeM0l       0   
2           accordion        accordion  https://imgur.com/GgGvdZR       0   
3               acorn            acorn  https://imgur.com/YfIB5lM       0   
4     air conditioner  air_conditioner  https://imgur.com/KqYNwWH       1   
...               ...              ...                        ...     ...   
1849             yoke             yoke  https://imgur.com/nOt3K3f       0   
1850             yolk             yolk  https://imgur.com/gWY0jPO       0   
1851            zebra            zebra  https://imgur.com/xg5AAHb       0   
1852           zipper           zipper  https://imgur.com/T2RLBxe       0   
1853         zucchini         zucchini  https://imgur.com/vEuESRM       0   

      Percent_known  Rank (combining COCA/concreteness)  Concreteness (M)  \
0              1.00                             18158.5              4.68   
1              0.93                             17741.0              4.52   
2              0.97                              8541.0              4.86   
3              1.00                              7723.5              4.96   
4              1.00                             12115.0              4.93   
...             ...                                 ...               ...   
1849           0.97                              9558.5              4.83   
1850           0.96                              7970.5              4.78   
1851           1.00                              8136.5              4.86   
1852           1.00                              6954.5              4.83   
1853           1.00                              6455.5              4.87   

      COCA word freq (online)  COCA word freq  COCA (dispersion)  ...  \
0                          53            28.0               0.78  ...   
1                         188            97.0               0.86  ...   
2                         816           735.0               0.90  ...   
3                        1289           692.0               0.85  ...   
4                         943             NaN                NaN  ...   
...                       ...             ...                ...  ...   
1849                      692           597.0               0.90  ...   
1850                      881          1224.0               0.89  ...   
1851                     1066           839.0               0.87  ...   
1852                     1478          1452.0               0.88  ...   
1853                     2098          1471.0               0.87  ...   

      Top-down Category (WordNet)  Top-down Category (manual selection)  \
0                          animal                                animal   
1                             NaN                            home decor   
2              musical instrument                    musical instrument   
3                           fruit                                   NaN   
4                             NaN                     electronic device   
...                           ...                                   ...   
1849                          NaN                                   NaN   
1850                         food                                  food   
1851                       animal                                animal   
1852                          NaN                                   NaN   
1853                    vegetable                       food, vegetable   

            All Bottom-up Categories  \
0                             animal   
1                mathematical device   
2                 musical instrument   
3                                nut   
4                     home appliance   
...                              ...   
1849  farm equipment, animal harness   
1850                     part of egg   
1851                         

Scelgo l'indice del paziente che voglio studiare

In [6]:
paziente = 11

Creo la stringa contenente l'indirizo del csv con i dati degli events del paziente che ho scelto

In [7]:
if paziente < 10:
    filename = os.path.join(home_path,"eeg","sub-0"+str(paziente),"eeg", "sub-0"+str(paziente)+"_task-rsvp_events.csv")
if paziente >= 10:
    filename = os.path.join(home_path,"eeg","sub-"+str(paziente),"eeg", "sub-"+str(paziente)+"_task-rsvp_events.csv")   
df_events = pd.read_csv(filename)

In [8]:
df_events

eventnumber  blocksequencenumber  isteststim        object  \
0                0                    0           0  light_switch   
1                1                    0           0       walker1   
2                2                    0           0     penholder   
3                3                    0           0     vegetable   
4                4                    0           0     swing_set   
...            ...                  ...         ...           ...   
24643        24643                   -1           1            -1   
24644        24644                   -1           1            -1   
24645        24645                   -1           1            -1   
24646        24646                   -1           1            -1   
24647        24647                   -1           1            -1   

       objectnumber  presentationnumber  sequencenumber  \
0               926                   0               0   
1              1773                   1               0   
2              1146                   2               0   
3              1754                   3               0   
4              1599                   4               0   
...             ...                 ...             ...   
24643            -1                 195              83   
24644            -1                 196              83   
24645            -1                 197              83   
24646            -1                 198              83   
24647            -1                 199              83   

                                            stim  stimnumber  teststimnumber  \
0      stimuli\light_switch\light_switch_09s.jpg           8              -1   
1                stimuli\walker1\walker1_12s.jpg          11              -1   
2            stimuli\penholder\penholder_01b.jpg           0              -1   
3            stimuli\vegetable\vegetable_02s.jpg           1              -1   
4            stimuli\swing_set\swing_set_02s.jpg           1              -1   
...                                          ...         ...             ...   
24643    stimuli\screwdriver\screwdriver_13s.jpg          -1             172   
24644                  stimuli\fish\fish_13s.jpg          -1             137   
24645  stimuli\mosquito_net\mosquito_net_13s.jpg          -1              67   
24646                  stimuli\baby\baby_17s.jpg          -1             103   
24647            stimuli\lasagna\lasagna_13s.jpg          -1              61   

       withinsequencenumber  istarget              stimname  response   rt  \
0                         0         0  light_switch_09s.jpg       0.0  0.0   
1                         0         0       walker1_12s.jpg       0.0  0.0   
2                         0         0     penholder_01b.jpg       0.0  0.0   
3                         0         0     vegetable_02s.jpg       0.0  0.0   
4                         0         0     swing_set_02s.jpg       0.0  0.0   
...                     ...       ...                   ...       ...  ...   
24643                    -1         0   screwdriver_13s.jpg       0.0  0.0   
24644                    -1         0          fish_13s.jpg       0.0  0.0   
24645                    -1         0  mosquito_net_13s.jpg       0.0  0.0   
24646                    -1         0          baby_17s.jpg       0.0  0.0   
24647                    -1         0       lasagna_13s.jpg       0.0  0.0   

       correct  time_stimon  time_stimoff   stimdur  
0          0.0    46.717538     46.767500  0.049962  
1          0.0    46.817527     46.867518  0.049992  
2          0.0    46.917542     46.967497  0.049956  
3          0.0    47.017551     47.067523  0.049972  
4          0.0    47.117549     47.167526  0.049977  
...        ...          ...           ...       ...  
24643      0.0  3169.946106   3169.996091  0.049984  
24644      0.0  3170.046105   3170.096079  0.049974  
24645      0.0  3170.146102   3170.196084  0.049982  
24646      0.0  3170.246111   3

Creo la stringa contenente l'indirizo dell'EEG pulito del paziente che ho scelto

In [9]:
file  = "sub-"+str(paziente)+"_task-rsvp_eeg.vhdr" #questo è il file non pulito, sostituitelo con il file preprocessato

In [10]:
if paziente < 10:
    filename = os.path.join(home_path,"eeg","sub-0"+str(paziente),"eeg", file)
if paziente >= 10:
    filename = os.path.join(home_path,"eeg","sub-"+str(paziente),"eeg", file)   

Importo l'EEG

In [11]:
eeg_clean = mne.io.read_raw_brainvision(filename, preload=True) 
#questa funzione sarà da modificare in base all'estensione del vostro file preprocessato

Extracting parameters from E:\Datasets\NL3\eeg\sub-11\eeg\sub-11_task-rsvp_eeg.vhdr...
Setting channel info structure...
Reading 0 ... 3226059  =      0.000 ...  3226.059 secs...


## Suddivido l'EEG in epochs/windows

Il nostro EEG ha solo le annotazioni, quindi le converto in eventi

In [12]:
events, event_id = mne.events_from_annotations(eeg_clean)    

Used Annotations descriptions: ['Event/E  1', 'Event/E  2', 'Event/E  3', 'New Segment/']


Grazie agli eventi ora segmento l'EEG in più windows 

In [13]:
epochs = mne.Epochs(eeg_clean, events, tmin=-0.1, tmax=1)

Not setting metadata
49381 matching events found
Setting baseline interval to [-0.1, 0.0] sec
Applying baseline correction (mode: mean)
0 projection items activated


Estraggo solo le epochs che registrano l'esperimento

In [14]:
data=epochs['10001']

## Estraggo le categorie e le ordino per poterle associare facilmente alle epochs corrispondenti

Estraggo la colonna 'objectnumber' da df_events e la converto in un array

In [15]:
obj_num=df_events['objectnumber']
num=obj_num.to_numpy()

Estraggo gli eventi dell'EEG

In [16]:
new_events=data.events

new_events

array([[  98347,       0,   10001],
       [  98447,       0,   10001],
       [  98547,       0,   10001],
       ...,
       [3221770,       0,   10001],
       [3221870,       0,   10001],
       [3221970,       0,   10001]])

Imposto come codice evento i numeri associati ai concepts di THINGS sfruttando il file .csv del paziente

In [17]:
for ii in np.arange(len(new_events[:])):
    new_events[ii][2]=num[ii]

In [18]:
new_events

array([[  98347,       0,     926],
       [  98447,       0,    1773],
       [  98547,       0,    1146],
       ...,
       [3221770,       0,      -1],
       [3221870,       0,      -1],
       [3221970,       0,      -1]])

Importo il dataframe dove sono raggruppate le categorie che ci servono (lo potete trovare nella mia cartella su OneDrive)

In [19]:
path_dataframe = os.path.join(home_path, 'cat_dataframe.csv')
cat_dataframe = pd.read_csv(path_dataframe,index_col=0)

Nuovo dizionario per gli events con i concepts associati alle macro-categorie

In [20]:
new_dict=cat_dataframe.T.to_dict(orient='list')
clean_dict={}

In [21]:
new_dict

{'animal': [0.0,
  12.0,
  15.0,
  25.0,
  26.0,
  34.0,
  53.0,
  75.0,
  87.0,
  105.0,
  107.0,
  112.0,
  128.0,
  130.0,
  131.0,
  134.0,
  146.0,
  151.0,
  214.0,
  236.0,
  241.0,
  245.0,
  284.0,
  287.0,
  315.0,
  321.0,
  323.0,
  326.0,
  332.0,
  334.0,
  349.0,
  371.0,
  387.0,
  404.0,
  406.0,
  423.0,
  426.0,
  427.0,
  428.0,
  434.0,
  471.0,
  476.0,
  487.0,
  495.0,
  496.0,
  497.0,
  502.0,
  504.0,
  525.0,
  545.0,
  554.0,
  578.0,
  600.0,
  601.0,
  602.0,
  603.0,
  638.0,
  644.0,
  666.0,
  675.0,
  684.0,
  688.0,
  694.0,
  695.0,
  718.0,
  722.0,
  743.0,
  761.0,
  774.0,
  781.0,
  798.0,
  815.0,
  825.0,
  845.0,
  862.0,
  875.0,
  884.0,
  889.0,
  907.0,
  909.0,
  917.0,
  933.0,
  937.0,
  938.0,
  939.0,
  964.0,
  992.0,
  1014.0,
  1016.0,
  1017.0,
  1018.0,
  1026.0,
  1042.0,
  1056.0,
  1057.0,
  1070.0,
  1080.0,
  1084.0,
  1085.0,
  1092.0,
  1105.0,
  1106.0,
  1145.0,
  1157.0,
  1170.0,
  1173.0,
  1198.0,
  1211.0,
  1220.

Questo dizionario ha gli elementi salvati come float e un sacco di nan inutili, quindi lo correggo

In [22]:
#for key_name in new_dict:
    
    #Creo items_cleaned tenendo solo gli elementi non nulli di ogni categoria
#    items_cleaned = [item for item in new_dict[key_name] if not np.isnan(item)]
    
    #Inserisco nel nuovo dizionario clean_dict la categoria come key a cui associo gli elementi appena ottenuti
#    clean_dict[key_name] = items_cleaned
    
    #Trasformo gli elementi ottenuti da float a int
#    clean_dict[key_name] = [int(val) for val in clean_dict[key_name]]

for key_name in new_dict:
    
    #Creo items_cleaned tenendo solo gli elementi non nulli di ogni categoria
    items_cleaned = []
    for item in new_dict[key_name]:
        if not np.isnan(item):
            items_cleaned.append(item)
    
    #Inserisco nel nuovo dizionario clean_dict la categoria come key a cui associo gli elementi appena ottenuti
    clean_dict[key_name] = items_cleaned
    
    temp=[]
    #Trasformo gli elementi ottenuti da float a int
    for val in clean_dict[key_name]:
        temp.append(int(val))
    clean_dict[key_name] = temp

Stampo le categorie che ho ottenuto

In [23]:
clean_dict.keys()

dict_keys(['animal', 'bird', 'body part', 'clothing', 'clothing accessory', 'container', 'dessert', 'drink', 'electronic device', 'food', 'fruit', 'furniture', 'home decor', 'insect', 'kitchen appliance', 'kitchen tool', 'medical equipment', 'musical instrument', 'office supply', 'part of car', 'plant', 'sports equipment', 'tool', 'toy', 'vegetable', 'vehicle', 'weapon', 'uncategorized'])

Associo ad ogni epoch un nuovo numero che mi identificherà la categoria dello stimolo

In [24]:
j=0

#Ciclo for per ogni window aiutandomi con la funzione ausiliaria column() che ho creato
for ii in column(new_events,2):
    k=0
    
    #Ciclo for per ogni categoria
    for key_name in clean_dict:
        
        #Se l'indice dello stimolo (ii) è tra i concepts associati alla categoria che sto considerando allora lo
        #cambio con un numero (k)
        if ii in clean_dict[key_name]:
            new_events[j][2]=k
            
        #Aumento k per non avere categorie con lo stesso indice
        k+=1
    
    #Aumento j per scorrere tutte le windows del paziente
    j+=1 


Ora tutte le windows hanno come indice un numero da -1 a 27

In [25]:
new_events

array([[  98347,       0,      27],
       [  98447,       0,      16],
       [  98547,       0,      18],
       ...,
       [3221770,       0,      -1],
       [3221870,       0,      -1],
       [3221970,       0,      -1]])

Associo ad ogni categoria un numero scorrendo tutte le categorie e aumentando di volta in volta k, così che corrispondando ai nuovi indici

In [26]:
k=0

for key_name in clean_dict:
    clean_dict[key_name]=k
    k+=1

#Il dataset associa agli stimoli di trial l'indice -1, quindi lo inserisco così anche nel nuovo dizionario
clean_dict['trial']=-1

Imposto i nuovi id degli eventi

In [27]:
data.event_id=clean_dict

In [28]:
data.event_id

{'animal': 0,
 'bird': 1,
 'body part': 2,
 'clothing': 3,
 'clothing accessory': 4,
 'container': 5,
 'dessert': 6,
 'drink': 7,
 'electronic device': 8,
 'food': 9,
 'fruit': 10,
 'furniture': 11,
 'home decor': 12,
 'insect': 13,
 'kitchen appliance': 14,
 'kitchen tool': 15,
 'medical equipment': 16,
 'musical instrument': 17,
 'office supply': 18,
 'part of car': 19,
 'plant': 20,
 'sports equipment': 21,
 'tool': 22,
 'toy': 23,
 'vegetable': 24,
 'vehicle': 25,
 'weapon': 26,
 'uncategorized': 27,
 'trial': -1}

In [29]:
data.events

array([[  98347,       0,      27],
       [  98447,       0,      16],
       [  98547,       0,      18],
       ...,
       [3221770,       0,      -1],
       [3221870,       0,      -1],
       [3221970,       0,      -1]])

Incorporo più categorie 'simili' sotto una più grande

In [30]:
animal_ext=['animal','bird','insect']
food_ext=['food','dessert','drink','fruit','vegetable']
tool_ext=['tool','electronic device','kitchen appliance','kitchen tool',
          'medical equipment','office supply','sports equipment','weapon']

Combino gli eventi di queste categorie 'simili' e vi associo un nuovo indice

In [31]:
mne.epochs.combine_event_ids(data,animal_ext,{'animal_ext':30},copy=False)
mne.epochs.combine_event_ids(data,food_ext,{'food_ext':31},copy=False)
mne.epochs.combine_event_ids(data,tool_ext,{'tool_ext':32},copy=False)

<Epochs |  24648 events (good & bad), -0.1 - 1 sec, baseline -0.1 – 0 sec, ~93 kB, data not loaded,
 'body part': 372
 'clothing': 1020
 'clothing accessory': 264
 'container': 468
 'furniture': 456
 'home decor': 216
 'musical instrument': 420
 'part of car': 300
 'plant': 576
 'toy': 540
 and 6 more events ...>

# Creazione Evokeds

Faccio la media tra gli stimoli della stessa categoria, ottenendo gli ERPs finali

In [32]:
animal=data['animal_ext'].average()
food=data['food_ext'].average()
tool=data['tool_ext'].average()
body=data['body part'].average()
vehicle=data['vehicle'].average()

Salvo i dati

In [33]:
...

Ellipsis

## Estrazione delle features

Estraggo le features di mio interesse (mne vi mette a disposizione delle funzioni per farlo :) )

In [34]:
...

Ellipsis